export const BACKEND_REGISTER_REQUEST = "BACKEND_REGISTER_REQUEST";
export const BACKEND_REGISTER_SUCCESS = "BACKEND_REGISTER_SUCCESS";
export const BACKEND_REGISTER_FAILURE = "BACKEND_REGISTER_FAILURE";

export const BACKEND_LOGIN_REQUEST = "BACKEND_LOGIN_REQUEST";
export const BACKEND_LOGIN_SUCCESS = "BACKEND_LOGIN_SUCCESS";
export const BACKEND_LOGIN_FAILURE = "BACKEND_LOGIN_FAILURE";

export const BACKEND_LOGOUT_REQUEST = "BACKEND_LOGOUT_REQUEST";
export const BACKEND_LOGOUT_SUCCESS = "BACKEND_LOGOUT_SUCCESS";
export const BACKEND_LOGOUT_FAILURE = "BACKEND_LOGOUT_FAILURE";
