
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const LOGOUT_SUCCESS= "LOGOUT_SUCCESS";

export const GITHUB_SUCCESS = "GITHUB_SUCCESS";

export const REQERS_LOGIN_REQUEST = "REQERS_LOGIN_REQUEST";
export const REQERS_LOGIN_SUCCESS = "REQERS_LOGIN_SUCCESS";
export const REQERS_LOGIN_FAILURE = "REQERS_LOGIN_FAILURE";

export const REQERS_LOGOUT_REQUEST = "REQERS_LOGOUT_REQUEST";
export const REQERS_LOGOUT_SUCCESS = "REQERS_LOGOUT_SUCCESS";
export const REQERS_LOGOUT_FAILURE = "REQERS_LOGOUT_FAILURE";

