export const LOADING_REQUEST = "LOADING_REQUEST";
export const POST_SUCCESS_REQUEST = "POST_SUCCESS_REQUEST";
export const FAILURE_REQUEST = "FAILURE_REQUEST";

export const GET_SUCCESS_REQUEST = "GET_SUCCESS_REQUEST";
export const PATCH_SUCCESS_REQUEST = "PATCH_SUCCESS_REQUEST";
